# Generated by Django 2.1.5 on 2019-01-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
