# Generated by Django 2.1.5 on 2019-01-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20190116_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
