# Generated by Django 2.1.5 on 2019-01-16 15:58

from django.db import migrations
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('announcement', '0003_announcement_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='views',
        ),
        migrations.AddField(
            model_name='announcement',
            name='views',
            field=gm2m.fields.GM2MField(through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
    ]
